<?php

declare(strict_types=1);

/*
 * Combat UI Symfony Bundle
 *
 * This source file is subject to the MIT license bundled with this package in the file LICENSE.
 *
 * @copyright Copyright (c) 2026 Combat Jongerenmarketing en -communicatie B.V. (https://www.combat.nl)
 * @license MIT https://opensource.org/licenses/MIT
 * @author Combat UI contributors
 */

namespace CombatUI\Bundle\CoreBundle\Twig\Node;

use CombatUI\Bundle\CoreBundle\Twig\ComponentRenderer;
use Twig\Compiler;
use Twig\Node\Expression\AbstractExpression;
use Twig\Node\Node;

/**
 * Compiled form of `{% cui %}`. Captures the tag body as the "default" slot (nested `{% cui_slot %}` tags register
 * named slots in `_cui_slots`) and delegates rendering to the `ComponentRenderer` runtime.
 */
final class ComponentNode extends Node
{
    public function __construct(AbstractExpression $name, ?AbstractExpression $props, Node $body, int $lineno)
    {
        $nodes = ['name' => $name, 'body' => $body];

        if ($props !== null) {
            $nodes['props'] = $props;
        }

        parent::__construct($nodes, [], $lineno);
    }

    /**
     * Compiles the node to PHP code. The compiled code captures the body of the tag as the "default" slot,
     * collects any named slots from nested `{% cui_slot %}` tags, and calls the `ComponentRenderer` runtime
     * to render the component.
     *
     * compiles the following code:
     * ```
     * $parentSlots = $context['_cui_slots'] ?? null;
     * $context['_cui_slots'] = [];
     * ob_start();
     * // Render the body of the tag, which may include nested `{% cui_slot %}` tags that register named slots in `$context['_cui_slots']`.
     * $this->subcompile($this->getNode('body'));
     * $slots = $context['_cui_slots'];
     * $slots['default'] = ob_get_clean();
     * if ($parentSlots !== null) {
     *     $context['_cui_slots'] = $parentSlots;
     * } else {
     *     unset($context['_cui_slots']);
     * }
     * echo $this->env->getRuntime(ComponentRenderer::class)->render($this->env, $this->getNode('name'), (array) ($this->hasNode('props') ? $this->getNode('props') : []), $slots);
     * ```
     *
     * @inheritDoc
     */
    public function compile(Compiler $compiler): void
    {
        $parentSlots = $compiler->getVarName();
        $slots = $compiler->getVarName();

        $compiler
            ->addDebugInfo($this)
            ->write(sprintf("\$%s = \$context['_cui_slots'] ?? null;\n", $parentSlots))
            ->write("\$context['_cui_slots'] = [];\n")
            ->write("ob_start();\n")
            ->subcompile($this->getNode('body'))
            ->write(sprintf("\$%s = \$context['_cui_slots'];\n", $slots))
            ->write(sprintf("\$%s['default'] = ob_get_clean();\n", $slots))
            ->write(sprintf("if (\$%s !== null) { \$context['_cui_slots'] = \$%s; } else { unset(\$context['_cui_slots']); }\n", $parentSlots, $parentSlots))
            ->write(sprintf("echo \$this->env->getRuntime(\%s::class)->render(\$this->env, ", ComponentRenderer::class))
            ->subcompile($this->getNode('name'))
            ->raw(", (array) (");

        if ($this->hasNode('props')) {
            $compiler->subcompile($this->getNode('props'));
        } else {
            $compiler->raw("[]");
        }

        $compiler->raw(sprintf("), \$%s);\n", $slots));


        parent::compile($compiler); // TODO: Change the autogenerated stub
    }
}
